version: '3.8'
services:
  oxox:
    image: klaus9267/oxox-backend
    container_name: oxox
    ports:
      - "8080:8080"
    environment:
      TZ: "Asia/Seoul"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"