spring:
  banner:
    charset: UTF-8
    location: classpath:banner.txt
  output:
    ansi:
      enabled: always
  profiles:
    active: db, server, swagger, auth, aws, monitor
  jackson:
    serialization:
      indent-output: true
bulk:
  password: test password