DROP TABLE IF EXISTS profiles CASCADE;
DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE "users" (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    uid VARCHAR(255)
);

CREATE TABLE "profiles" (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    emoji VARCHAR(255),
    nickname VARCHAR(255) NOT NULL,
    sequence BIGINT NOT NULL,
    user_id BIGINT,
    FOREIGN KEY (user_id) REFERENCES users(id)
);